"""Shared paths for the tutorial notebooks. `%run ../tutorial_config.py` to load.

Inputs (VIDEO_PATH, QUERY_IMAGE) are committed under data/tutorial/. Outputs are
regenerated by the notebooks under data/outputs/ (gitignored). The 01->07 chain is
self-contained: no gcloud, no pre-baked artifacts.
"""

from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parents[3]  # docs/source/tutorials/ -> repo root
_TUT_DATA = REPO_ROOT / "data" / "tutorial"
MAX_FRAMES = 30

# ── Committed inputs (read-only) ──────────────────────────────────────────────
VIDEO_PATH = _TUT_DATA / "tutorial_example-video.mp4"
QUERY_IMAGE = _TUT_DATA / "tutorial_example-frame.jpg"

# ── Generated outputs (gitignored; notebooks write here) ──────────────────────
OUTPUT_DIR = REPO_ROOT / "data" / "outputs"
FRAMES_ZARR = OUTPUT_DIR / "frames.zarr"          # canonical keyframes (nb 01 writes)
RECON = OUTPUT_DIR / "feedforward.zarr"           # canonical reconstruction (nb 02 writes)
CACHE_DIR = OUTPUT_DIR                             # alias kept for notebook readability
TUTORIAL_CACHE = OUTPUT_DIR / "tutorial_cache"    # notebook scratch (plots, ae caches)

if not VIDEO_PATH.exists():
    raise FileNotFoundError(f"missing {VIDEO_PATH} — see data/tutorial/README.md (git clone should provide it)")
