"""Shared paths for the tutorial notebooks. `%run ../tutorial_config.py` to load.

Inputs (VIDEO_PATH, QUERY_IMAGE) are committed under data/tutorial/. Outputs are
regenerated by the notebooks under data/outputs/ (gitignored). The 01->07 chain is
self-contained: no gcloud, no pre-baked artifacts.
"""

from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parents[3]  # docs/source/tutorials/ -> repo root
MAX_FRAMES = 30

# ── Committed inputs (read-only) ──────────────────────────────────────────────
VIDEO_PATH = REPO_ROOT / "data/tutorial/tutorial_example-video.mp4"
QUERY_IMAGE = REPO_ROOT / "data/tutorial/tutorial_example-frame.jpg"

# ── Generated outputs (gitignored; notebooks write here) ──────────────────────
OUTPUT_DIR = REPO_ROOT / "data/outputs"
IMAGES_DIR = OUTPUT_DIR / "images"                # canonical keyframes (nb 01 writes)
RECON = OUTPUT_DIR / "pointcloud.zarr"            # canonical reconstruction (nb 02 writes)
TUTORIAL_CACHE = OUTPUT_DIR / "tutorial_cache"    # notebook scratch (plots, ae caches)

if not VIDEO_PATH.exists():
    raise FileNotFoundError(f"missing {VIDEO_PATH} — see data/tutorial/README.md (git clone should provide it)")
