########################################################################
# Video metadata and streamed decode
########################################################################

import inspect
import shutil
import subprocess
from pathlib import Path

import av
import numpy as np
import pytest

from collab_splats.preproc import video
from collab_splats.preproc.video import (
    _rotation_degrees,
    extract_frame,
    get_video_info,
    iter_frames,
)

# The rotated fixture, generated by tests/preproc/data/make_rotated_fixture.py
ROTATED = Path(__file__).parent / "data" / "rotated_90.mp4"


def test_get_video_info_keys(tiny_video):
    info = get_video_info(tiny_video)
    assert set(info) == {"total_frames", "fps", "duration_s", "width", "height"}


def test_get_video_info_values(tiny_video):
    info = get_video_info(tiny_video)
    assert info["total_frames"] == 60
    assert info["fps"] == pytest.approx(30.0)
    assert (info["width"], info["height"]) == (320, 240)
    assert info["duration_s"] == pytest.approx(2.0)


def test_get_video_info_missing_file():
    info = get_video_info("/nonexistent/video.mp4")
    assert info["total_frames"] == 0 and info["fps"] == 0.0


def test_get_video_info_frame_count_is_exact(tiny_video):
    """
    PyAV reads the count off the container — no full demux, no packet count.
    """
    info = get_video_info(tiny_video)

    assert info["total_frames"] > 0
    assert info["fps"] > 0
    assert abs(info["duration_s"] - info["total_frames"] / info["fps"]) < 0.05


def test_get_video_info_has_no_count_frames_flag():
    """
    The -count_packets full demux is gone; there is no cheap/expensive split left.
    """
    assert "count_frames" not in inspect.signature(get_video_info).parameters


def test_iter_frames_has_no_info_parameter():
    """
    It hoisted a probe the PyAV decode never makes; nothing may pass it again.
    """
    assert "info" not in inspect.signature(iter_frames).parameters


def test_get_video_info_returns_zeros_for_a_non_video(tmp_path):
    """
    An unprobeable file returns the zeros dict rather than raising.
    """
    bad = tmp_path / "not_a_video.mp4"
    bad.write_bytes(b"nope")

    assert get_video_info(bad)["total_frames"] == 0


def test_iter_frames_yields_index_and_bgr(tiny_video):
    out = list(iter_frames(tiny_video))
    total = get_video_info(tiny_video)["total_frames"]

    assert len(out) == total
    assert [i for i, _ in out] == list(range(total))
    assert out[0][1].ndim == 3 and out[0][1].dtype == np.uint8


def test_iter_frames_indices_yields_only_those(tiny_video):
    wanted = [0, 3, 7]

    out = list(iter_frames(tiny_video, indices=wanted))

    assert [i for i, _ in out] == wanted


def test_iter_frames_indices_matches_full_decode(tiny_video):
    everything = {i: f for i, f in iter_frames(tiny_video)}

    for idx, frame in iter_frames(tiny_video, indices=[1, 4]):
        assert np.array_equal(frame, everything[idx])


def test_iter_frames_range_matches_full_decode(tiny_video):
    everything = {i: f for i, f in iter_frames(tiny_video)}

    out = list(iter_frames(tiny_video, start=2, count=3))

    assert [i for i, _ in out] == [2, 3, 4]
    for idx, frame in out:
        assert np.array_equal(frame, everything[idx])


def test_iter_frames_rejects_indices_with_a_range(tiny_video):
    with pytest.raises(ValueError, match="indices"):
        list(iter_frames(tiny_video, indices=[1], start=2))


def test_video_module_uses_no_subprocess(tiny_video, monkeypatch):
    """
    Probe and both decode paths run in-process; no ffmpeg pipe, nothing on PATH.
    """
    monkeypatch.setattr(subprocess, "Popen", lambda *a, **k: pytest.fail("spawned an ffmpeg pipe"))
    monkeypatch.setattr(subprocess, "run", lambda *a, **k: pytest.fail("spawned an ffmpeg pipe"))

    assert get_video_info(ROTATED)["width"] == 180
    assert len(list(iter_frames(tiny_video, indices=[0, 2]))) == 2
    assert extract_frame(tiny_video, 4).shape == (240, 320, 3)


def test_iter_frames_yields_bgr(tiny_video):
    """
    Colour convention is unchanged: iter_frames is BGR, extract_frame is RGB.
    """
    _, bgr = next(iter(iter_frames(tiny_video)))
    rgb = extract_frame(tiny_video, 0)

    assert np.abs(bgr[..., ::-1].astype(int) - rgb.astype(int)).max() <= 2


def test_iter_frames_indices_yields_exactly_those_indices(tiny_video):
    """
    Scattered reads come back in ascending order, once each.
    """
    got = [i for i, _ in iter_frames(tiny_video, indices=[7, 2, 2, 5])]

    assert got == [2, 5, 7]


def test_iter_frames_start_count_window(tiny_video):
    """
    start/count is a contiguous window in source frame indices.
    """
    got = [i for i, _ in iter_frames(tiny_video, start=4, count=3)]

    assert got == [4, 5, 6]


def test_iter_frames_stops_early_without_decoding_the_tail(tiny_video):
    """
    The last requested index ends the scan; the rest of the file is not decoded.
    """
    total = get_video_info(tiny_video)["total_frames"]
    assert total > 20

    got = [i for i, _ in iter_frames(tiny_video, indices=[1, 3])]
    assert got == [1, 3]


def test_iter_frames_deep_window_lands_on_the_right_frames(tiny_video):
    """
    A window far enough in to seek past a keyframe still reports absolute indices.
    """
    everything = {i: f for i, f in iter_frames(tiny_video)}

    out = list(iter_frames(tiny_video, start=40, count=5))

    assert [i for i, _ in out] == [40, 41, 42, 43, 44]
    for idx, frame in out:
        assert np.array_equal(frame, everything[idx])


def test_iter_frames_missing_file_yields_nothing():
    """
    An unopenable path is empty, not an exception — the samplers rely on it.
    """
    assert list(iter_frames("/nonexistent/video.mp4")) == []


def test_extract_frame_accepts_a_preprobed_info(tiny_video):
    info = get_video_info(tiny_video)

    assert np.array_equal(extract_frame(tiny_video, 2, info=info), extract_frame(tiny_video, 2))


def test_extract_frame_matches_the_scan(tiny_video):
    """
    Seeking to frame N returns the same pixels the scan yields at N.
    """
    scanned = dict(iter_frames(tiny_video, indices=[12]))
    seeked = extract_frame(tiny_video, 12)

    assert np.abs(scanned[12][..., ::-1].astype(int) - seeked.astype(int)).max() <= 2


def test_extract_frame_rejects_an_out_of_range_index(tiny_video):
    """
    Past the end is an error, not a silently-clamped last frame.
    """
    total = get_video_info(tiny_video)["total_frames"]

    with pytest.raises(ValueError, match="out of range"):
        extract_frame(tiny_video, total + 5)


########################################################################
# extract_frame: input-seek single-frame decode for previews
########################################################################

# These build their fixtures with the ffmpeg binary (testsrc, and a rotate=90
# remux of it), so they are skipped rather than failed when it is absent.
requires_ffmpeg = pytest.mark.skipif(shutil.which("ffmpeg") is None, reason="ffmpeg required")


@pytest.fixture(scope="module")
def synth_video(tmp_path_factory):
    # 2s of 30fps testsrc — 60 frames, constant frame rate
    path = tmp_path_factory.mktemp("vid") / "synth.mp4"
    subprocess.run(
        [
            "ffmpeg",
            "-v",
            "error",
            "-f",
            "lavfi",
            "-i",
            "testsrc=duration=2:size=320x240:rate=30",
            "-pix_fmt",
            "yuv420p",
            str(path),
        ],
        check=True,
    )
    return path


@pytest.fixture(scope="module")
def rotated_video(synth_video, tmp_path_factory):
    """synth_video re-muxed with a rotate=90 tag — display dims swap to (240, 320)."""
    path = tmp_path_factory.mktemp("vid_rot") / "rotated.mp4"
    # Stream copy + rotate tag: same pixels, ffmpeg autorotates on decode
    subprocess.run(
        [
            "ffmpeg",
            "-v",
            "error",
            "-i",
            str(synth_video),
            "-c",
            "copy",
            "-metadata:s:v:0",
            "rotate=90",
            str(path),
        ],
        check=True,
    )
    return path


@requires_ffmpeg
def test_extract_frame_shape_and_dtype(synth_video):
    frame = extract_frame(synth_video, 30)
    assert frame.shape == (240, 320, 3)
    assert frame.dtype == np.uint8


@requires_ffmpeg
def test_extract_frame_lands_near_target_index(synth_video):
    # testsrc's content changes every frame; a correctly-seeked decode must differ
    # less from its immediate neighbour than from a distant frame (catches gross
    # seek errors, e.g. landing many frames off target).
    frame_30 = extract_frame(synth_video, 30)
    frame_31 = extract_frame(synth_video, 31)
    frame_0 = extract_frame(synth_video, 0)
    d_adjacent = np.abs(frame_30.astype(int) - frame_31.astype(int)).mean()
    d_far = np.abs(frame_30.astype(int) - frame_0.astype(int)).mean()
    assert d_adjacent < d_far


@requires_ffmpeg
def test_extract_frame_rotated_video_matches_display_dims(rotated_video):
    # The display matrix is applied on decode: extract_frame's dims must match
    # get_video_info's display dims (which already account for the rotate tag),
    # consistent with the streamed decode it shares a path with.
    info = get_video_info(str(rotated_video))
    frame = extract_frame(rotated_video, 0)
    assert frame.shape[:2] == (info["height"], info["width"])


########################################################################
# Container display rotation
########################################################################


def test_rotation_degrees_reads_the_display_matrix():
    """
    The fixture carries a 90-degree CW display matrix; PyAV is the only reader.
    """
    with av.open(str(ROTATED)) as container:
        assert _rotation_degrees(container) == 90


def test_rotation_degrees_is_zero_without_a_display_matrix(tiny_video):
    """
    An unrotated container decodes to rotation 0 rather than raising.
    """
    with av.open(str(tiny_video)) as container:
        assert _rotation_degrees(container) == 0


def test_rotated_fixture_reports_display_dimensions():
    """
    The fixture is 320x180 stored, 180x320 displayed. get_video_info reports displayed.
    """
    info = get_video_info(ROTATED)

    assert (info["width"], info["height"]) == (180, 320)


def test_rotated_fixture_decodes_upright():
    """
    ffmpeg auto-rotates, and whatever replaces it must too: decoded frames match
    the reported display dimensions.
    """
    info = get_video_info(ROTATED)
    _, frame = next(iter_frames(ROTATED))

    assert frame.shape[:2] == (info["height"], info["width"]) == (320, 180)


########################################################################
# get_video_info: frame count for containers without nb_frames
########################################################################


@requires_ffmpeg
def test_get_video_info_falls_back_to_duration_x_rate(synth_video, tmp_path):
    """
    mpeg-ts carries no nb_frames, so stream.frames is 0 and duration x rate stands in.
    """
    # Stream-copy the 60-frame fixture into a container that drops the count
    ts_path = tmp_path / "synth.ts"
    subprocess.run(["ffmpeg", "-v", "error", "-i", str(synth_video), "-c", "copy", str(ts_path)], check=True)
    with av.open(str(ts_path)) as container:
        assert container.streams.video[0].frames == 0

    assert get_video_info(ts_path)["total_frames"] == 60


def test_video_no_longer_exports_context_indices():
    """
    context_indices moved to sampling; video.py decodes, it does not select.
    """
    assert not hasattr(video, "context_indices")
